### PR TITLE
Increase AWS MediaPackage HLS segment duration

### PR DESCRIPTION
**Pull request by EdNutting**
To reduce the probability of triggering [the VideoJS segment buffering bug](https://github.com/videojs/http-streaming/issues/1000#issuecomment-899934566)

## What's improved

By increasing the segment duration from 1s to 5s, we hopefully reduce the probability of triggering the VideoJS client-side segment buffering bug by ~5x. Assuming probability works at scale the way I hope (and there are no other unintended side effects), this should dramatically reduce the impact on our end users while we wait for VideoJS to come up with a proper fix.

## Details

- [Related issue on VideoJS HTTP Streaming](https://github.com/videojs/http-streaming/issues/1000#issuecomment-899934566)

## Upgrading and Deployment

Instructions for how to deploy these changes to production. Please tick (i.e.
put an 'x' in) the boxes for the actions that are necessary.

- [ ] Apply migrations to Hasura
- [ ] Apply metadata to Hasura
- [ ] Reload enum table/values in Hasura for [table names]
- [ ] Re-deploy frontend
- [ ] Re-deploy actions service
- [x] Re-deploy playout service
- [ ] Re-deploy real-time service
- [ ] Flush real-time service state (Redis/RabbitMQ)
- [ ] Update environment variables for [name of component]

Any other steps necessary to re-deploy?

I honestly am not sure - I think any existing MediaLive endpoints probably have to be deleted so they can be recreated?

### CODE REVIEW

**Comment by EdNutting** [comment]
I have tested this by manually making the change in one of our existing test streaming environments and it does appear to have prevented my original reproduction steps from retriggering the original issue.

@rossng If we aren't confident merging/deploying this, I have tested in AWS tonight and we can edit the MediaPackage endpoint directly to test it tomorrow.

**Comment by rossng** [comment]
Is it necessary to go to 5s? This will significantly increase latency.

**Comment by EdNutting** [comment]
Yes. Unless we can fix the video player, all users receiving video reliably is far more preferable than 25% of the audience missing most of the talk because the player keeps freezing.

**Review by rossng — APPROVED** [review]
That is a fair argument, and a small price to pay for better reliability right now.

IMPORTANT: you must tear down and re-create and existing channel stacks to benefit from this code change. Or you can manually edit the MediaPackage channel in AWS.

**Pull request merged**
