### PR TITLE
Features/starring events

### PR DESCRIPTION
**Pull request by EdNutting**
Introduces starring events.

* "Stars" appear next to events (item page, exhibition page, all schedule views, event modal)
* Clicking stars adds/remove them to/from My Events
* My Events modal (under My Stuff) allows someone to see both the events they have starred and events they are listed as an Event Person on.
* Download ICalendar file button on all schedule views
   * Eventually we should offer an iCal URL for people to subscribe to - but that requires a serverside function and a dedicated url

### CODE REVIEW

**Comment by EdNutting** [comment]
One thing I have just thought of: This might cause appalling numbers of GQL requests when someone opens the Whole Schedule view. A request is sent for every event box that needs to load the "starred" status. So, CLSummit for example, with 156 events, would issue 156 GQL requests the instant someone loads the Whole Schedule view :/

**Comment by rossng** [comment]
You could perhaps lazy-load the data using https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API to determine what is currently in-view? There's also [batching](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/) in Apollo but I don't think you can set it to only apply to one query.

**Comment by EdNutting** [comment]
Yes - already using the intersection observer API in the chat message list view so this shouldn't be too challenging to add.

**Comment by EdNutting** [comment]
Performance impact significantly reduced. The starred state will now only load in when the button is visible and after a 250ms delay (so when the browser is auto-scrolling to now or to a particular day, it doesn't trigger loading the starred state of every event that passes by only for a fleeting moment).

**Pull request merged**
