### PR TITLE
Match SECRET_FOR_FLUSHING and SECRET_FOR_SUMMARY on Realtime and Hasura sample env files

### PR DESCRIPTION
**Pull request by shawnsp**
Please ensure your PR title includes the relevant emoji signifiers. See
[CONTRIBUTING] for details.

## What's [new / improved / fixed]

- Match SECRET_FOR_FLUSHING and SECRET_FOR_SUMMARY on both Realtime and Hasura env.example files
- Update realtime/README.md

## Details

- Related issue:  #307

## Upgrading

Instructions for other developers on how to upgrade their environment after
pulling this new code. Please tick (i.e. put an 'x' in) the boxes for the
actions that are necessary.

- [ ] Run GraphQL Codegen in the [frontend/actions service/playout service/realtime service]
- [ ] Re-install NPM packages in [insert name of folder]
- [ ] Apply Hasura migrations
- [ ] Apply Hasura metadata
- [ ] Update Auth0 rules
- [ ] Update environment variables
- [ ] Re-deploy AWS CDK [and update AWS environment variables]

## Deployment

Instructions for how to deploy these changes to production. Please tick (i.e.
put an 'x' in) the boxes for the actions that are necessary.

- [ ] Apply migrations to Hasura
- [ ] Apply metadata to Hasura
- [ ] Reload enum table/values in Hasura for [table names]
- [ ] Re-deploy frontend
- [ ] Re-deploy actions service
- [ ] Re-deploy playout service
- [ ] Re-deploy real-time service
- [ ] Flush real-time service state (Redis/RabbitMQ)
- [ ] Update environment variables for [name of component]

Any other steps necessary to re-deploy?

### CODE REVIEW

**Review by rossng — CHANGES_REQUESTED** [review]
I think it's possible a file is missing from this PR? Either `hasura/.env.example` or `services/realtime/.env.example` should be modified to actually set matching default values.

**Comment by shawnsp** [comment]
Hi Ross, I just double check that my previous changes are made on only these two files:
1.  services/realtime/.env.example, swapped SECRET_FOR_FLUSHING and SECRET_FOR_SUMMARY.
2. services/realtime/README.md,  added some descriptions related to SECRET_FOR_FLUSHING and SECRET_FOR_SUMMARY. 

Let me know if the issue still remains.

**Comment by EdNutting** [comment]
Hi,

I think the point Ross may have been trying to make is that the values for `SECRET_FOR_FLUSHING` and `SECRET_FOR_SUMMARY` have not been corrected. They are still `my_secret`, which do not match the values in `hasura/.env.example` (where they are `ZZZZZ` and `YYYYY` respectively).

Please update the values in `services/realtime/.env.example` to be `YYYYY`/`ZZZZZ` accordingly, so the values in the two env files match.

Thanks,
Ed

**Comment by shawnsp** [comment]
Hi Ed, thanks for the clarification. I have made the change according to that.

**Pull request merged**
